# Generated by Django 3.2.10 on 2021-12-14 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guid', models.UUIDField(unique=True, verbose_name='GUID')),
                ('coord', models.JSONField()),
                ('weather', models.JSONField()),
                ('main', models.JSONField()),
                ('wind', models.JSONField()),
                ('fetched_location', models.CharField(max_length=30)),
                ('searched_location', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
