version: "3"

services:
  web:
    build: .
    volumes:
      - .:/django
    ports:
      - "8000:8000"
    image: weather:django
    container_name: weather_backend_container
    command: >
      sh -c "python manage.py migrate && 
             python manage.py runserver 0.0.0.0:8000
             "
    depends_on:
      - db

#    environment:
#      - DB_HOST=db
#      - DB_NAME=weather_app_db
#      - DB_USER=postgres
#      - DB_PASS=postgres
#    depends_on:
#      - db

  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=weather_app_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
#     ports:
#       - "5432:5432"
#    expose:
#      - "5440"
